package com.kafsys.common.enums;

public enum AlertType {
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    TRANSACTION_ROLLED_BACK,
    LARGE_TRANSACTION,
    SUSPICIOUS_ACTIVITY,
    ACCOUNT_SUSPENDED,
    KYC_VERIFIED,
    INSUFFICIENT_FUNDS
}
